### ISSUE TITLE
no exception catched from Django management command 

### ISSUE THREAD

**Issue by kakulukia** [getsentry/raven-python#1006]
according to this example:
https://github.com/getsentry/raven-python/blob/master/examples/django_110/app/management/commands/example.py

there is nothing special to do when creating a management command, but my exceptions are not logged :/

im using Django 1.11.1 and the example command above

**Comment by kakulukia** [comment]
adding those two lines to my command:
from raven.contrib.django.raven_compat.models import client
client.captureException()

results into this exception:
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/andy/projects/GuK/core/management/commands/run_msb_client.py", line 11, in handle
    client.captureException()
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/raven/base.py", line 799, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/raven/contrib/django/client.py", line 292, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/raven/base.py", line 615, in capture
    elif not self.should_capture(exc_info):
  File "/Users/andy/.virtualenvs/GuK-WKWTomJd/lib/python3.6/site-packages/raven/base.py", line 803, in should_capture
    exc_name = '%s.%s' % (exc_type.__module__, exc_type.__name__)
AttributeError: 'NoneType' object has no attribute '__module__'

**Comment by mattrobenolt** [comment]
This looks like you're trying to capture an exception when there is no exception to be captured.

**Comment by kakulukia** [comment]
@mattrobenolt im raising the Exception right after 
client.captureException()
putting the capture command below the possible exception position aint making any sense since that position wont ever be reached by the python interpreter.

Like i said im using the example command, which i linked above, and since its not working in the vanilla version i put those two lines in the middle .. so we got the following result:

    from django.core.management.base import BaseCommand
    
    
    class Command(BaseCommand):
        help = 'Examples'
    
        def handle(self, *args, **options):
            from raven.contrib.django.raven_compat.models import client
            client.captureException()
            raise Exception('oops')'''

**Comment by mattrobenolt** [comment]
Right, and the code you posted won't work becasue there's not a current exception happening. You'd need to do that inside of an `except`.

Something like:

```python
try:
  raise Exception('oops')
except Exception:
  client.captureException()
```

As for why it's not happening automatically, I'm not sure. I don't think we've tested against 1.11 to see if behavior has changed any. I'd have to spend some time to investigate.

**Comment by kakulukia** [comment]
Okay, your solution works, but this kind of defeats the whole purpose of automatically catching  any exception :/

I just downgraded my installed Django version to 1.10.7 with the same result of not reporting the error. Inside a view it works tho.

**Comment by mattrobenolt** [comment]
Yeah, agreed. :) What version of raven do you have installed? At some point, we did have this broken, then we fixed it.

**Comment by kakulukia** [comment]
i have version 6.0.0
