### ISSUE TITLE
object of type 'DjangoClient' has no len()

### ISSUE THREAD

**Issue by jleclanche** [getsentry/raven-python#1025]
Getting this on AWS Lambda with Python 3.6 runtime:

```pytb
Traceback (most recent call last):
File "/var/task/hsreplaynet/utils/instrumentation.py", line 112, in wrapper
if sentry:
File "/var/task/raven/contrib/django/models.py", line 69, in <lambda>
__len__ = lambda x: len(get_client())
TypeError: object of type 'DjangoClient' has no len()
```

That `if sentry` is doing a bool() on a `raven.contrib.django.raven_compat.models.client` object. This works fine on 2.7, not on 3.6 which calls `__len__` when defined (and it is defined [here](https://github.com/getsentry/raven-python/blob/c63cc64f2b2214f0451c26edb3cba65b8c9144ae/raven/contrib/django/models.py#L69)).

**Comment by GrigoriyMikhalkin** [comment]
Problem still exists in `raven 6.9.0`

**Comment by xnightsky** [comment]
Problem still exists in raven 6.10.0

**Comment by MartinFalatic** [comment]
Is this bug being worked on?
