### ISSUE TITLE
Import Behavior / Recursive Errors

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-python#1032]
We're specifically seeing this in Sentry, but it means its possible elsewhere to. The issue is with importing ``django.conf.settings`` in the same module that has the implementation of ``SENTRY_CLIENT`` defined.

```
:56:45 server          | Python auto-reloader enabled
16:56:45 server          |   File "/Users/dcramer/Development/sentry/src/sentry/wsgi.py", line 22, in <module>
16:56:45 server          |     configure()
16:56:45 server          |   File "/Users/dcramer/Development/sentry/src/sentry/runner/__init__.py", line 123, in configure
16:56:45 server          |     configure(ctx, py, yaml, skip_service_validation)
16:56:45 server          |   File "/Users/dcramer/Development/sentry/src/sentry/runner/settings.py", line 153, in configure
16:56:45 server          |     }, skip_service_validation=skip_service_validation)
16:56:45 server          |   File "/Users/dcramer/Development/sentry/src/sentry/runner/initializer.py", line 243, in initialize_app
16:56:45 server          |     configure_structlog()
16:56:45 server          |   File "/Users/dcramer/Development/sentry/src/sentry/runner/initializer.py", line 235, in configure_structlog
16:56:45 server          |     logging.config.dictConfig(settings.LOGGING)
16:56:45 server          |   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 794, in dictConfig
16:56:45 server          |     dictConfigClass(config).configure()
16:56:45 server          |   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 559, in configure
16:56:45 server          |     'filter %r: %s' % (name, e))
16:56:45 server          | ValueError: Unable to configure filter 'sentry:internal': 'module' object has no attribute 'SentryInternalClient'
16:56:45 server          | unable to load app 0 (mountpoint='') (callable not found or import error)
```

Trying to debug this real quick to see what we changed to cause this, but it was something from the 6.0.0 release AFAIK.

**Comment by dcramer** [comment]
Changed import logic in 6.0:

```diff 
+from django.utils.datastructures import MultiValueDict
-from raven.contrib.django.middleware import SentryLogMiddleware
+from raven.contrib.django.middleware import SentryMiddleware
+from raven.utils.compat import string_types, binary_type, iterlists
+from raven.contrib.django.resolver import RouteResolver
-from raven._compat import string_types, binary_type
```

**Comment by dcramer** [comment]
Easiest way to repro is load up Sentry, kill the raven pinned requirement in setup.py, pip install -e raven-python into it, and then sentry shell:

```
dcramer:sentry in ~/Development/sentry on git:master+?
$ sentry shell
from sentry.app imTraceback (most recent call last):
  File "/Users/dcramer/.virtualenvs/sentry/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/Users/dcramer/Development/sentry/src/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/runner/__init__.py", line 93, in inner
    ctx.forward(django)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/Users/dcramer/Development/sentry/src/sentry/runner/__init__.py", line 123, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/Users/dcramer/Development/sentry/src/sentry/runner/settings.py", line 153, in configure
    }, skip_service_validation=skip_service_validation)
  File "/Users/dcramer/Development/sentry/src/sentry/runner/initializer.py", line 243, in initialize_app
    configure_structlog()
  File "/Users/dcramer/Development/sentry/src/sentry/runner/initializer.py", line 235, in configure_structlog
    logging.config.dictConfig(settings.LOGGING)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 559, in configure
    'filter %r: %s' % (name, e))
ValueError: Unable to configure filter 'sentry:internal': 'module' object has no attribute 'SentryInternalClient'
```

**Comment by dcramer** [comment]
I lied, the issue is in 6.1.0

**Comment by dcramer** [comment]
I think the culprit is:

```diff
+        # instantiate client so hooks get registered
+        get_client()  # NOQA
```
