### ISSUE TITLE
raven middleware iter error

### ISSUE THREAD

**Issue by yangjiaronga** [getsentry/raven-python#1043]
```
From cffi callback <function uwsgi_pypy_wsgi_handler at 0x00007f8047616548>:
Traceback (most recent call last):
  File "c callback", line 472, in uwsgi_pypy_wsgi_handler
  File "/usr/local/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/site-packages/raven/middleware.py", line 99, in __call__
    return ClosingIterator(self, iterable, environ)
  File "/usr/local/site-packages/raven/middleware.py", line 47, in __init__
    self.iterable = iter(iterable)
TypeError: iter() returned non-iterator
```

```
from raven import Client
from raven.contrib.celery import register_signal, register_logger_signal

client = Client(__DNS__)

# register a custom filter to filter out duplicate logs
register_logger_signal(client)

# The register_logger_signal function can also take an optional argument
# `loglevel` which is the level used for the handler created.
# Defaults to `logging.ERROR`
register_logger_signal(client, loglevel=logging.INFO)

# hook into the Celery error handler
register_signal(client)
```
pypy 5.8.0
flask 0.12
i  pypy run.py then raise this error
how to solve？ thinks

**Comment by mitsuhiko** [comment]
This is likely caused by uwsgi not following the WSGI spec under pypy: https://github.com/unbit/uwsgi/issues/291

We can try to catch down that error but there is not much we can do about this :(
