### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'connection_pool'

### ISSUE THREAD

**Issue by xoco70** [getsentry/raven-python#1062]
After an internal bug reported by Sentry telling me I had an old version of raven, I updated to raven 5.33.0.

After restarting supervisorctl, Sentry was not working anymore ( 502 Bad Gateway )

I decided to upgrade sentry
`source bin/activate`
`pip install --upgrade sentry #This Command is OK` 
`sentry upgrade #This Command Failed --> No module Named Error` 

I tried to regenerated conf files ( config.yml and sentry.conf.py) but it didn't work.

I backed up those 2 files before operation, and then compare them so I'm pretty sure the config is ok.

In my nginx logs, I have : 

2017/08/22 08:55:03 [error] 2638#2638: *3116 connect() failed (111: Connection refused) while connecting to upstream, client: 176.158.217.87, server: bugs.kendozone.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://127.0.0.1:9000/favicon.ico", host: "bugs.kendozone.com", referrer: "https://bugs.kendozone.com/"

Here is my nginx config:

```
server {
    listen   443 ssl http2;
    server_name bugs.kendozone.com;
    
    ssl_certificate /etc/nginx/ssl/bugs.kendozone.com/229137/server.crt;
    ssl_certificate_key /etc/nginx/ssl/bugs.kendozone.com/229137/server.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    proxy_set_header   Host                 $host;
    proxy_set_header   X-Forwarded-Proto    $scheme;
    proxy_set_header   X-Forwarded-For      $remote_addr;
    proxy_redirect     off;

    # keepalive + raven.js is a disaster
    keepalive_timeout 0;

    # use very aggressive timeouts
    proxy_read_timeout 15s;
    proxy_send_timeout 15s;
    send_timeout 15s;
    resolver_timeout 15s;
    client_body_timeout 15s;

    # buffer larger messages
    client_max_body_size 15m;
    client_body_buffer_size 100k;

    location / {
      proxy_pass        http://localhost:9000;

      add_header Strict-Transport-Security "max-age=31536000";
    }
  }

```

Now, When I try to upgrade , I get : 

(forge) root@ip-172-31-2-201:~# sentry upgrade
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/forge/local/lib/python2.7/site-packages/raven/base.py", line 249, in handle_exception
    self.captureException(exc_info=exc_info, level='fatal')
  File "/home/forge/local/lib/python2.7/site-packages/raven/base.py", line 781, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 43, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 284, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/raven/base.py", line 610, in capture
    self.send(**data)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 64, in send
    from sentry.coreapi import ClientApiHelper
  File "/home/forge/local/lib/python2.7/site-packages/sentry/coreapi.py", line 28, in <module>
    from sentry import filters
  File "/home/forge/local/lib/python2.7/site-packages/sentry/filters/__init__.py", line 8, in <module>
    from .base import Filter  # NOQA
  File "/home/forge/local/lib/python2.7/site-packages/sentry/filters/base.py", line 5, in <module>
    from sentry.models import ProjectOption
  File "/home/forge/local/lib/python2.7/site-packages/sentry/models/__init__.py", line 14, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 52, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/home/forge/local/lib/python2.7/site-packages/sentry/models/deploy.py", line 11, in <module>
    from sentry.app import locks
  File "/home/forge/local/lib/python2.7/site-packages/sentry/app.py", line 15, in <module>
    from sentry.utils.locking.backends.redis import RedisLockBackend
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/locking/backends/redis.py", line 10, in <module>
    delete_lock = redis.load_script('utils/locking/delete_lock.lua')
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 145, in load_script
    script = Script(None, resource_string('sentry', posixpath.join('scripts', path)))
  File "/home/forge/local/lib/python2.7/site-packages/redis/client.py", line 2930, in __init__
    encoder = registered_client.connection_pool.get_encoder()
AttributeError: 'NoneType' object has no attribute 'connection_pool'

Original exception was:
Traceback (most recent call last):
  File "/home/forge/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/forge/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/forge/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/forge/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/forge/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 123, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 152, in configure
    skip_service_validation=skip_service_validation
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 288, in initialize_app
    register_plugins(settings)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 22, in register_plugins
    from sentry.plugins import plugins
  File "/home/forge/local/lib/python2.7/site-packages/sentry/plugins/__init__.py", line 10, in <module>
    from sentry.plugins.base import *  # NOQA
  File "/home/forge/local/lib/python2.7/site-packages/sentry/plugins/base/__init__.py", line 10, in <module>
    from .bindings import BindingManager
  File "/home/forge/local/lib/python2.7/site-packages/sentry/plugins/base/bindings.py", line 5, in <module>
    from sentry.plugins import providers
  File "/home/forge/local/lib/python2.7/site-packages/sentry/plugins/providers/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 52, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/home/forge/local/lib/python2.7/site-packages/sentry/plugins/providers/base.py", line 9, in <module>
    from sentry.models import Integration, OrganizationIntegration
  File "/home/forge/local/lib/python2.7/site-packages/sentry/models/__init__.py", line 14, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 52, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/home/forge/local/lib/python2.7/site-packages/sentry/models/deploy.py", line 11, in <module>
    from sentry.app import locks
  File "/home/forge/local/lib/python2.7/site-packages/sentry/app.py", line 15, in <module>
    from sentry.utils.locking.backends.redis import RedisLockBackend
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/locking/backends/redis.py", line 10, in <module>
    delete_lock = redis.load_script('utils/locking/delete_lock.lua')
  File "/home/forge/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 145, in load_script
    script = Script(None, resource_string('sentry', posixpath.join('scripts', path)))
  File "/home/forge/local/lib/python2.7/site-packages/redis/client.py", line 2930, in __init__
    encoder = registered_client.connection_pool.get_encoder()
AttributeError: 'NoneType' object has no attribute 'connection_pool'

**Comment by mattrobenolt** [comment]
It seems you reported this in the wrong repo. But the problem is `redis-py` released an API breaking change in a patch version release. 2.10.5 ->2.10.6. We’ve pinned this more strictly on master, but you can work around this in the meantime by just doing `pip install redis==2.10.5`.

**Comment by xoco70** [comment]
Ohh yes, you're right... sorry for that, it's not the good repo! Will try it! Tx
