### ISSUE TITLE
Django command fails with --data option.

### ISSUE THREAD

**Issue by Petelin** [getsentry/raven-python#1078]
`python manage.py raven --data "{'as':1}"  test`
```
(pycharm_cadus) [~/Documents/gitlib/cadus]$ pip show django                               [feature/maidan] 
Name: Django
Version: 1.10
(pycharm_cadus) [~/Documents/gitlib/cadus]$ pip show celery                               [feature/maidan] 
Name: celery
Version: 4.0.2
```
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zhangxiaolin/.virtualenvs/pycharm_cadus/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/zhangxiaolin/.virtualenvs/pycharm_cadus/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/zhangxiaolin/.virtualenvs/pycharm_cadus/lib/python3.5/site-packages/django/core/management/base.py", line 299, in run_from_argv
    options = parser.parse_args(argv[2:])
  File "/Users/zhangxiaolin/.virtualenvs/pycharm_cadus/lib/python3.5/site-packages/django/core/management/base.py", line 58, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/zhangxiaolin/.virtualenvs/pycharm_cadus/lib/python3.5/site-packages/raven/contrib/django/management/commands/raven.py", line 24, in __call__
    setattr(namespace, self.dest, store_json(values[0]))
TypeError: store_json() missing 3 required positional arguments: 'opt_str', 'value', and 'parser'
```

i use this version in product env, so i have no update raven to see if this bud have fix. i read source code, it is because `store_json` need `(option, opt_str, value, parser) `but 
```
class StoreJsonAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, store_json(values[0]))
```
if alread fix, sorry to bother.

**Comment by ashwoods** [comment]
@Petelin thx for reporting the issue. careful with the `"{'as':1}"`, as it is not valid JSON.
