### ISSUE TITLE
Python v2.7 and raven v6.1.0 , server returns 404

### ISSUE THREAD

**Issue by hmilkovi** [getsentry/raven-python#1083]
Hey there,
I have latest Sentry server 8.20.0, Django 1.11.4, Raven 6.1.0 and Python v2.7.10.

Server isn't the problem as I can send events via curl.
For some reason even cli command  ` raven test <dsn> ` returns 404 http error from urllib2.

Url is correct tryed with curl, my first guess would be the body of request or auth is wrong.

As raven cli doesn't return any stacktrace here is what I got from `python manage.py raven test ` : 

```
Traceback (most recent call last):
  File "/Users/hmilkovi/src/kraken/kwiki/backend/venv/lib/python2.7/site-packages/raven/transport/threaded.py", line 172, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/Users/hmilkovi/src/kraken/kwiki/backend/venv/lib/python2.7/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/Users/hmilkovi/src/kraken/kwiki/backend/venv/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

Thx, any info will help.

**Comment by ashwoods** [comment]
I can't reproduce this with my any of my tests environments. You can test your environment by creating a bare virtualenv with only raven installed and run `raven test <dsn>` to help troubleshoot your issue.

**Comment by hmilkovi** [comment]
@ashwoods yep, I created new  ` virtualenv `.
pip freeze:
```
contextlib2==0.5.5
raven==6.1.0
```

raven test <dsn>:
```
Using DSN configuration:
  http://**********************:**********************@sentry.hrvoje.hr/18

Client configuration:
  base_url       : http://sentry.hrvoje.hr
  project        : 18
  public_key     : **********************
  secret_key     : **********************

Sending a test message... Event ID was '6571e9f720f24f3b81c7589de6e05591'
No handlers could be found for logger "sentry.errors"
error!
```

**Comment by ashwoods** [comment]
@hmilkovi You might want to add a handler and set logging to debug. My guess is that the problem lays somehow on your system configuration, and is not a bug, but hard to say without more info.

**Comment by hmilkovi** [comment]
Oke I tasted it now with free account on https://sentry.io so and it worked.
Thx for all help 👍 . Now I see that maybe there is an issue with self hosted sentry server.
