### ISSUE TITLE
Django 2.0: AttributeError: 'URLResolver' object has no attribute 'regex'

### ISSUE THREAD

**Issue by jleclanche** [getsentry/raven-python#1148]
If an error happens in a middleware's `process_view()` with Django 2.0, the following error happens in Raven:

```py
Traceback (most recent call last):
  File "/home/adys/src/HearthSim/HSReplay.net/.tox/py36/lib/python3.6/site-packages/raven/contrib/django/middleware/__init__.py", line 101, in process_view
    client.get_transaction_from_request(request)
  File "/home/adys/src/HearthSim/HSReplay.net/.tox/py36/lib/python3.6/site-packages/raven/contrib/django/client.py", line 309, in get_transaction_from_request
    return self.resolver.resolve(request.path)
  File "/home/adys/src/HearthSim/HSReplay.net/.tox/py36/lib/python3.6/site-packages/raven/contrib/django/resolver.py", line 88, in resolve
    match = self._resolve(resolver, path)
  File "/home/adys/src/HearthSim/HSReplay.net/.tox/py36/lib/python3.6/site-packages/raven/contrib/django/resolver.py", line 53, in _resolve
    match = resolver.regex.search(path)
AttributeError: 'URLResolver' object has no attribute 'regex'
```

**Comment by jleclanche** [comment]
Sorry, should have looked more closely, this is #1127.

**Comment by arvind2289** [comment]
where is anser

**Comment by LaundroMat** [comment]
You need to [upgrade to >=6.4.0](https://github.com/getsentry/raven-python/issues/1127#issuecomment-353259024).
