### ISSUE TITLE
Flask + gunicorn + gevent TypeError when instantiating

### ISSUE THREAD

**Issue by kamac** [getsentry/raven-python#1150]
I've been trying to get raven to run with flask + gevent stack, with little success. I was able to get it to work without gevent worker class, but with gunicorn as WSGI, which required me to set my config up like this:

```
SENTRY_DSN = 'my_dsn_here'
SENTRY_CONFIG = {
    'environment': 'production',
}
```

Then I tried to run the app with gevent as worker class. This stack trace popped up:

```
Traceback (most recent call last):
[...]
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 104, in __init__
    self.init_app(app)
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 184, in init_app
    self.client = make_client(self.client_cls, app, self.dsn)
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 48, in make_client
    'app': app,
  File "/usr/local/lib/python3.6/site-packages/raven/base.py", line 193, in __init__
    self._context = Context()
  File "/usr/local/lib/python3.6/site-packages/gevent/local.py", line 244, in __new__
    self = object.__new__(cls)
TypeError: Can't instantiate abstract class Context with abstract methods __len__
```

I tried to set up gevented transport layer like this:

```
SENTRY_DSN = 'my_dsn_here'
SENTRY_CONFIG = {
    'environment': 'production',
    'transport': 'raven.transport.gevent.GeventedHTTPTransport'
}
```

But nothing has changed. I think the exception throws before init_app is called, because "Running with ProductionConfig" is printed after the stack trace. Here's how i setup the application:

```
from raven.contrib.flask import Sentry
from flask.helpers import get_debug_flag
import flask

sentry = None
def create_app():
    app = flask.Flask(__name__, static_url_path='/assets', static_folder='static/assets')
    config_class = 'DevelopmentConfig' if get_debug_flag() else 'ProductionConfig'
    app.config.from_object('app.config.{}'.format(config_class))
    print("Running with " + config_class)

    global sentry
    sentry = Sentry()
    return app
```

Same error occurs when running with eventlet as worker class:

```
Traceback (most recent call last):
[...]
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 104, in __init__
    self.init_app(app)
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 184, in init_app
    self.client = make_client(self.client_cls, app, self.dsn)
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/flask.py", line 48, in make_client
    'app': app,
  File "/usr/local/lib/python3.6/site-packages/raven/base.py", line 193, in __init__
    self._context = Context()
  File "/usr/local/lib/python3.6/site-packages/eventlet/corolocal.py", line 19, in __new__
    self = object.__new__(cls)
TypeError: Can't instantiate abstract class Context with abstract methods __len__
```

**Comment by kamac** [comment]
I'm sorry, it turns out I've been using version **3.6.0** instead of the newest **6.3.0**. After updating everything's working just fine... Gosh xd

**Comment by ashwoods** [comment]
:D no worries.
