### ISSUE TITLE
Test failures in 6.4.0 release

### ISSUE THREAD

**Issue by felixonmars** [getsentry/raven-python#1164]
The failures are not present in the previous 6.3.0 version. I have tested it with both Python 3.6 and 2.7 but got the same errors:

```
=================================== FAILURES ===================================
_________________ BreadcrumbTestCase.test_log_crumb_reporting __________________
Traceback (most recent call last):
  File "/build/python-raven/src/raven-python-6.4.0-py2/tests/breadcrumbs/tests.py", line 28, in test_log_crumb_reporting
    log.info('This is a message with %s!', 'foo', blah='baz')
  File "/usr/lib/python2.7/logging/__init__.py", line 1159, in info
    Log 'msg % args' with severity 'INFO'.
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'blah'
------------------------------ Captured log call -------------------------------
base.py                    265 DEBUG    Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f0a459bced0>
_________ SentryExceptionHandlerTest.test_does_exclude_filtered_types __________
Traceback (most recent call last):
  File "/build/python-raven/src/raven-python-6.4.0-py2/tests/contrib/django/tests.py", line 889, in test_does_exclude_filtered_types
    assert not mock_send.called
AssertionError: assert not True
 +  where True = <MagicMock name='send' id='139682075695248'>.called
------------------------------ Captured log call -------------------------------
base.py                    628 INFO     Not capturing exception due to filters: <type 'exceptions.ValueError'>
ValueError: lol world
___ SentryExceptionHandlerTest.test_ignore_exceptions_with_expression_match ____
Traceback (most recent call last):
  File "/build/python-raven/src/raven-python-6.4.0-py2/tests/contrib/django/tests.py", line 905, in test_ignore_exceptions_with_expression_match
    assert not mock_send.called
AssertionError: assert not True
 +  where True = <MagicMock name='send' id='139682072405904'>.called
------------------------------ Captured log call -------------------------------
base.py                    628 INFO     Not capturing exception due to filters: <type 'exceptions.ValueError'>
ValueError: lol world
_____ SentryExceptionHandlerTest.test_ignore_exceptions_with_module_match ______
Traceback (most recent call last):
  File "/build/python-raven/src/raven-python-6.4.0-py2/tests/contrib/django/tests.py", line 921, in test_ignore_exceptions_with_module_match
    assert not mock_send.called
AssertionError: assert not True
 +  where True = <MagicMock name='send' id='139682072404752'>.called
------------------------------ Captured log call -------------------------------
base.py                    628 INFO     Not capturing exception due to filters: <type 'exceptions.ValueError'>
ValueError: lol world
```

Some more version info:
```
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.1, py-1.5.0, pluggy-0.6.0
Django settings: tests.contrib.django.settings (from ini file)
rootdir: /build/python-raven/src/raven-python-6.4.0, inifile: setup.cfg
plugins: timeout-1.2.1, django-3.1.3.dev0+ng7aee367.d20161226, cov-2.5.1, celery-4.1.0, case-1.5.3
```

**Comment by felixonmars** [comment]
That did the trick. Many thanks!
