### ISSUE TITLE
Sentry responded with an error: HTTP Error 403: OK

### ISSUE THREAD

**Issue by justin76tan** [getsentry/raven-python#1172]
I use django, raven-python version is 6.4.0
python manage.py raven --traceback test
Client configuration:
  base_url       : http://120.24.249.69:9000/sentry
  project        : 2
  public_key     : 2acf61cecdd24a7b922c9416af5e1fe3
  secret_key     : c18ac29d6cf54792983f55dde6182f95

Sending a test message... Event ID was '3a0153965d834802a22ffca24a8b4fec'
Sentry responded with an error: HTTP Error 403: OK (url: http://120.24.249.69:9000/sentry/api/2/store/)
Traceback (most recent call last):
  File "/home/deploy/act_python35x/lib/python3.5/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/home/deploy/act_python35x/lib/python3.5/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/home/deploy/act_python35x/lib/python3.5/site-packages/raven/utils/http.py", line 73, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: OK
['This is a test message generated using ``raven test``']

**Comment by ashwoods** [comment]
@justin76tan Can you curl your server with an example payload? Or try out `sentry-cli`? My guess is that the problem might be on the server side.

**Comment by justin76tan** [comment]
@ashwoods Thank you reply, this problem is solved. There is problem in Sentry's help information, which hint dsn is  http://120.24.249.69:9000/sentry//2,  but real dsn is  http://120.24.249.69:9000/2.

**Comment by exploser** [comment]
The above discrepancy was solved for me by removing trailing slash from Root URL in settings

**Comment by anghelflorin** [comment]
I had a similar issue with Sentry deployed on K8s. The problem in my case was the DSN was pointing to the `sentry-web` service but it should've been `sentry-nginx` service. So I had to create two ingress routes, sentry-web was used for the web interface and sentry-nginx to send events from my app.
