### ISSUE TITLE
Django project in subversion, raven does not work

### ISSUE THREAD

**Issue by ccpwcn** [getsentry/raven-python#1308]
Project: Django
OS: Windows 10
code manage: subversion
in setting.py:
```
import raven
RAVEN_CONFIG = {
    'dsn': 'https://xxx@sentry.io/nnn',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(BASE_DIR),
}
```
When I have errors:
```
Traceback (most recent call last):
  File "E:/code/PycharmProjects/pss_patent/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\django\conf\__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "E:\code\PycharmProjects\pss_patent\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\code\PycharmProjects\pss_patent\pss_patent\settings.py", line 23, in <module>
    'release': raven.fetch_git_sha(BASE_DIR),
  File "E:\code\PycharmProjects\pss_patent\venv\lib\site-packages\raven\versioning.py", line 19, in fetch_git_sha
    'Cannot identify HEAD for git repository at %s' % (path,))
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository at E:\code\PycharmProjects\pss_patent
```
I had lookup a lot of informations, All of body said: I needed git, but My project is in subversion, How can I resolve it???

**Comment by untitaker** [comment]
Then set the release explicitly

**Comment by ccpwcn** [comment]
> Then set the release explicitly

How can I set it? I cannot find the subversion configuration information in raven's documents.
