### ISSUE TITLE
TypeError w/ __repr__ when using plone/zope

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/raven-python#1310]
A user reports that whenever an OPTIONS request is made to a Plone application (running Zope) this issue occurs:

```
==> client2-event.log <== 
------ 
2018-11-27T09:58:57 ERROR Zope.SiteErrorLog 1543283937.330.238564883427 https://website.com/file.txt 
Traceback (innermost last): 
Module ZPublisher.Publish, line 127, in publish 
Module ZPublisher.BaseRequest, line 479, in traverse 
Module zope.browserresource.file, line 94, in browserDefault 
AttributeError: 'FileResource' object has no attribute 'OPTIONS' 
------ 
2018-11-27T09:58:57 ERROR sentry.errors.serializer unbound method __repr__() must be called with Application instance as first argument (got nothing instead) 
Traceback (most recent call last): 
File "/home/plone/eggs/raven-6.8.0-py2.7.egg/raven/utils/serializer/manager.py", line 76, in transform 
return repr(value) 
TypeError: unbound method __repr__() must be called with Application instance as first argument (got nothing instead) 
------ 
2018-11-27T09:58:57 ERROR sentry.errors.serializer unbound method __repr__() must be called with Application instance as first argument (got nothing instead) 
Traceback (most recent call last): 
File "/home/plone/eggs/raven-6.8.0-py2.7.egg/raven/utils/serializer/manager.py", line 76, in transform 
return repr(value) 
TypeError: unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
```

This has also been reported [here](https://community.plone.org/t/attributeerror-and-unbound-method---repr---for-an-otherwise-working-object/3238).

**Comment by mitsuhiko** [comment]
The issue is silenced already it’s just that the logger still shows up. Just silence the error logger in this case.

The actual bug is somewhere in zope.
