### ISSUE TITLE
6.10.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [getsentry/raven-python#1368]
```
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing raven.egg-info/PKG-INFO
writing dependency_links to raven.egg-info/dependency_links.txt
writing entry points to raven.egg-info/entry_points.txt
writing requirements to raven.egg-info/requires.txt
writing top-level names to raven.egg-info/top_level.txt
reading manifest file 'raven.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt'
warning: no files found matching '*' under directory 'raven/data'
warning: no previously-included files matching '*~' found anywhere in distribution
writing manifest file 'raven.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "setup.py", line 115, in run_tests
    errno = pytest.main(self.pytest_args)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/config.py", line 167, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/config.py", line 1084, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest-3.2.5-py3.8.egg/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/pytest_cov-2.5.1-py3.8.egg/pytest_cov/plugin.py", line 6, in <module>
    from coverage.misc import CoverageException
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/__init__.py", line 10, in <module>
    from coverage.control import coverage, process_startup
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/control.py", line 14, in <module>
    from coverage.html import HtmlReporter
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/html.py", line 8, in <module>
    from coverage.phystokens import source_token_lines, source_encoding
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/phystokens.py", line 5, in <module>
    from coverage.parser import generate_tokens
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/parser.py", line 321, in <module>
    OP_BREAK_LOOP = _opcode('BREAK_LOOP')
  File "/home/tkloczko/rpmbuild/BUILD/raven-6.10.0/.eggs/coverage-3.7.1-py3.8-linux-x86_64.egg/coverage/parser.py", line 280, in _opcode
    return dis.opmap[name]
KeyError: 'BREAK_LOOP'
```

**Comment by kloczek** [comment]
Closing.
It was my fault.
