### ISSUE TITLE
No way to pass tags from logbook.SentryHandler

### ISSUE THREAD

**Issue by fayazkhan** [getsentry/raven-python#266]
I've looked at the code and don't see any way any `tags` can be attached to a message from `raven.handlers.logbook.SentryHandler`

**Comment by johnofcamas** [comment]
That merge definitely did not solve this issue.  I'm getting:
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    logger.debug('Hello', tags={'user': 'dexter'})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1145, in debug
    Log 'msg % args' with severity 'DEBUG'.
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1153, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'tags'
```

When trying 
`logger.debug('Hello', tags={'user': 'dexter'})`

Any thoughts @fayazkhan

**Comment by fayazkhan** [comment]
You're using `logging`, not `logbook` which this patch is for.
