### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp sometimes

### ISSUE THREAD

**Issue by nuklea** [getsentry/raven-python#368]
```bash
$ pip freeze | egrep 'gevent|raven'
gevent==0.13.8
raven==3.5.0
```

Sometimes in logs:

```python
Top level Sentry exception caught - failed creating log record <open file '<stderr>', mode 'w' at 0x7f155e9101e0>
(0.000) SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1 ; args=(1,) <open file '<stderr>', mode 'w' at 0x7f155e9101e0>
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/handlers/logging.py", line 63, in emit
    return self._emit(record)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/contrib/django/handlers.py", line 29, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/handlers/logging.py", line 172, in _emit
    extra=extra, date=date, **kwargs)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/contrib/django/client.py", line 155, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/base.py", line 459, in capture
    **kwargs)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/contrib/django/client.py", line 107, in build_msg
    data = super(DjangoClient, self).build_msg(*args, **kwargs)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/base.py", line 281, in build_msg
    handler = self.get_handler(event_type)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/base.py", line 228, in get_handler
    return self.module_cache[name](self)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/raven/events.py", line 22, in __init__
    self.logger = logging.getLogger(__name__)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1556, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1023, in getLogger
    _acquireLock()
  File "/usr/lib64/python2.7/logging/__init__.py", line 217, in _acquireLock
    _lock.acquire()
  File "/usr/lib64/python2.7/threading.py", line 168, in acquire
    if self.__owner == me:
RuntimeError: maximum recursion depth exceeded in cmp
 <open file '<stderr>', mode 'w' at 0x7f155e9101e0>
```

**Comment by aolieman** [comment]
This is prohibiting me from setting any log levels lower than `WARNING`. Any new insights?

**Comment by dcramer** [comment]
The current unreleased version Sentry uses its own client and does not allow these kinds of errors.

**Comment by bkad** [comment]
Seeing this error in v5.4.0 in the tornado client:

```python
Top level Sentry exception caught - failed creating log record
max_clients limit reached, request queued. 10 active, 7367 queued requests.
Traceback (most recent call last):
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/handlers/logging.py", line 68, in emit
    return self._emit(record)
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/handlers/logging.py", line 179, in _emit
    extra=extra, date=date, **kwargs)
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/contrib/tornado/__init__.py", line 35, in capture
    data = self.build_msg(*args, **kwargs)
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/base.py", line 281, in build_msg
    handler = self.get_handler(event_type)
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/base.py", line 240, in get_handler
    return self.module_cache[name](self)
  File "/opt/ingestion/venv/lib/python2.7/site-packages/raven/events.py", line 22, in __init__
    self.logger = logging.getLogger(__name__)
  File "/usr/lib/python2.7/logging/__init__.py", line 1559, in getLogger
    return Logger.manager.getLogger(name)
RuntimeError: maximum recursion depth exceeded
```

Was the fix you described for the synchronous client?

**Comment by dcramer** [comment]
If this is in Raven and not Sentry you need to ensure that its own logger isnt trying to send to Sentry
