### ISSUE TITLE
Incompatible with celery==3.1.6 ?

### ISSUE THREAD

**Issue by dreampuf** [getsentry/raven-python#390]
```bash
[2013-12-05 06:21:09,123: CRITICAL/MainProcess] Task task.sync_note[48e9a697-fc04-4dc8-b248-4cd524bd305e] INTERNAL ERROR: AttributeError("'Celery' object has no attribute 'captureException'",)
Traceback (most recent call last):
  File "/home/dreampuf/www/tblog/.py/lib/python2.7/site-packages/celery/app/trace.py", line 235, in trace_task
    R = I.handle_error_state(task, eager=eager)
  File "/home/dreampuf/www/tblog/.py/lib/python2.7/site-packages/celery/app/trace.py", line 84, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/home/dreampuf/www/tblog/.py/lib/python2.7/site-packages/celery/app/trace.py", line 124, in handle_failure
    einfo=einfo)
  File "/home/dreampuf/www/tblog/.py/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 150, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/dreampuf/www/tblog/.py/lib/python2.7/site-packages/raven/contrib/celery/__init__.py", line 47, in process_failure_signal
    client.captureException(
AttributeError: 'Celery' object has no attribute 'captureException'
```

**Comment by dcramer** [comment]
Raven's documentation (I believe) fully entails how to integrate with 3.1 these days.

**Comment by galonsky** [comment]
hi @xordoquy @dcramer - I realize this is an old issue, but I think it's still relevant. With the recommended configuration for celery from Sentry, we've found that only errors logged from the root logger are getting to Sentry, but errors logged from task loggers (`get_task_logger`) are not getting to Sentry.

I've experimented with @baratrion's solution above, and it seems to work for both loggers (specifically, setting a signal on BOTH `after_setup_logger` and `after_setup_task_logger`)

Since the task logger is the preferred way to log in celery tasks (adds context relevant to the task instance), I think raven should support this logger.

**Comment by galonsky** [comment]
@GVRV I did something like this below (@baratrion's idea):
```python
def add_sentry_handler_to_task_loggers(client, loglevel=logging.ERROR):
    """
    Similar to what raven's `register_logger_signal` does, but registers
    the celery `after_setup_task_logger` to add the SentryHandler to all
    celery task loggers (register_logger_signal only registers the signal
    to configure global loggers)
    """
    filter_ = CeleryFilter()

    handler = SentryHandler(client)
    handler.setLevel(loglevel)
    handler.addFilter(filter_)
    handler.setFormatter(TaskFormatter())

    def process_logger_event(
        sender, logger, loglevel, logfile, format, colorize, **kwargs
    ):
        logger.addHandler(handler)

    # See http://docs.celeryproject.org/en/latest/userguide/signals.html#after-setup-task-logger
    after_setup_task_logger.connect(process_logger_event, weak=False)
```

**Comment by GVRV** [comment]
@galonsky That works beautifully! Thank you!
