### ISSUE TITLE
TypeError: {'_accessed_time': 1395811784.374168, '_creation_time': 1395811784.374168} is not JSON serializable

### ISSUE THREAD

**Issue by zopyx** [getsentry/raven-python#440]
I am trying to get Plone 4.3 running with Sentry/raven. 
In order to check the functionality I wrote a script in Plone that triggers a simple
DivisionError. However this causes the following raven failure.
Also updating to Raven 4.1.1 did not help.

Traceback (most recent call last):
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/handlers/logging.py", line 64, in emit
    return self._emit(record)
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/handlers/logging.py", line 173, in _emit
    extra=extra, date=date, **kwargs)
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/base.py", line 494, in capture
    self.send(**data)
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/base.py", line 564, in send
    message = self.encode(data)
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/base.py", line 599, in encode
    return base64.b64encode(zlib.compress(json.dumps(data).encode('utf8')))
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/utils/json.py", line 52, in dumps
    return json.dumps(value, cls=BetterJSONEncoder, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/srv/gehirn/dasgehirn_buildout-debug/eggs/raven-4.0.4-py2.7.egg/raven/utils/json.py", line 39, in default
    return super(BetterJSONEncoder, self).default(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {'_accessed_time': 1395811784.374168, '_creation_time': 1395811784.374168} is not JSON serializable

**Comment by xordoquy** [comment]
Closing this since it's stalled. Feel free to reopen if anything new jumps in
