### ISSUE TITLE
Random failures on heroku

### ISSUE THREAD

**Issue by alexex** [getsentry/raven-python#500]
Hey everyone,

I have a project where I experience random sentry failures due to multiple bugs. I have absolutely NO idea why they are happening, but in 98% of the cases bugs are not tracked to the sentry log server. I am running the official sentry on https://app.getsentry.com/ and raven-python==5.0.0.

So far I have seen these two error backtraces:

```
Unable to reach Sentry log server: '' (url: https://app.getsentry.com/api/<project_id>/store/) 
Traceback (most recent call last): 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/transport/threaded.py", line 159, in send_sync 
  super(ThreadedHTTPTransport, self).send(data, headers) 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/transport/http.py", line 49, in send 
  ca_certs=self.ca_certs, 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen 
  return opener.open(url, data, timeout) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 404, in open 
  response = self._open(req, data) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 422, in _open 
  '_open', req) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 382, in _call_chain 
  result = func(*args) 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open 
  return self.do_open(ValidHTTPSConnection, req) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 1187, in do_open 
  r = h.getresponse(buffering=True) 
File "/app/.heroku/python/lib/python2.7/httplib.py", line 1067, in getresponse 
  response.begin() 
File "/app/.heroku/python/lib/python2.7/httplib.py", line 409, in begin 
  version, status, reason = self._read_status() 
File "/app/.heroku/python/lib/python2.7/httplib.py", line 373, in _read_status 
  raise BadStatusLine(line) 
BadStatusLine: ''
```

```
Unable to reach Sentry log server: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> (url: https://app.getsentry.com/api/<project_id>/store/) 
Traceback (most recent call last): 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/transport/threaded.py", line 159, in send_sync 
  super(ThreadedHTTPTransport, self).send(data, headers) 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/transport/http.py", line 49, in send 
  ca_certs=self.ca_certs, 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen 
  return opener.open(url, data, timeout) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 404, in open 
  response = self._open(req, data) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 422, in _open 
  '_open', req) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 382, in _call_chain 
  result = func(*args) 
File "/app/.heroku/python/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open 
  return self.do_open(ValidHTTPSConnection, req) 
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 1184, in do_open 
  raise URLError(err) 
URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> 
Failed to submit message: u"ObjectDeletedError: Instance '<PaymentTask at 0x7f4114900e50>' has been deleted, or its row is otherwise not present." 
```

Additionally I have a lot of errors where my application raises an error, flask also shows my error page and heroku also logs 500 as the http status code but no reporting happens whatsoever:

```heroku/router:  at=info method=GET path="/user/" host=<app>.herokuapp.com request_id=<request_id> fwd="<ip>" dyno=web.1 connect=2ms service=442ms status=500 bytes=6223 ```

I would very much appreciate any help on this because this problem is basically rendering sentry useless as an error tracker. :(

Thanks!

**Comment by xordoquy** [comment]
Does this still happen ?

**Comment by alexex** [comment]
As suggested by @dcramer I activated the sync mode (by prepending `sync+` to my url). Since that day the problem has disappeared.

**Comment by xordoquy** [comment]
ok, thanks for the feedback.
