### ISSUE TITLE
'NoneType' object has no attribute 'human_state'

### ISSUE THREAD

**Issue by inabhi9** [getsentry/raven-python#533]
I'm using raven in one of my projects with Django 1.7, Celery v3.1.17, Sentry 6.4.4 and Raven 5.1.1

Logging works fine with Django logger but when I start celery worker, it shows following exception in console before starting the worker. although worker starts and can perform tasks but logging to sentry doesn't work.

```
'NoneType' object has no attribute 'human_state'
Traceback (most recent call last):
  File "/home/abhinav/.virtualenvs/newsbyme-api/local/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/home/abhinav/.virtualenvs/newsbyme-api/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 329, in __repr__
    self=self, state=self.blueprint.human_state(),
AttributeError: 'NoneType' object has no attribute 'human_state'
'NoneType' object has no attribute 'human_state'
```

My Configuration file is looks like this

```
RAVEN_CONFIG = {
    'dsn': 'http://58abcd7e570543cbb13f6a0141f54c4d:8c75af6eee484e228a481b94e08fc41d@sentry.lan/2',
}
CELERYD_HIJACK_ROOT_LOGGER = False
SENTRY_AUTO_LOG_STACKS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': 'DEBUG',
        'handlers': ['sentry'],
    },
    'loggers': {
        'celery': {
            'level': 'ERROR',
            'handlers': ['sentry'],
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'sentry': {
            'level': 'DEBUG',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'verbose'
        },
    }
}
```

I've Googled why it is happening, but I couldn't found anything.

Anything I missed?

**Comment by omjangir** [comment]
remove *.pyc files
