### ISSUE TITLE
ImportError: No module named events

### ISSUE THREAD

**Issue by michaelmaltese** [getsentry/raven-python#552]
Seeing this occasionally:

```
Traceback (most recent call last):
  File "releases/latest/env/bin/my_cli_tool", line 9, in <module>
    load_entry_point('my_cli_tool==0.0.0', 'console_scripts', 'my_cli_tool')()
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__  
    return self.main(*args, **kwargs)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/my_cli_tool/__init__.py", line 675, in my_cli_tool
    run_tool()
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 686, in wrapper   
    self.captureException(**kwargs)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 658, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 508, in capture   
    **kwargs)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 286, in build_msg 
    handler = self.get_handler(event_type)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 237, in get_handler
    return self.module_cache[name](self)
  File "releases/28c91ce31a76d547dab93767dc7a208f8ddd7a10/env/local/lib/python2.7/site-packages/raven/base.py", line 49, in __missing__
    module, {}, {}, [class_name]), class_name)
ImportError: No module named events
```

seemingly with no cause.

I can `import raven.events`, so I'm not sure why this message is popping up.

**Comment by dcramer** [comment]
Do you have a module named raven elsewhere in your projects?

**Comment by xordoquy** [comment]
Closing this as we can't investigate further. Feel free to reopen if you have more informations about this.

**Comment by muthukumarclay** [comment]
Getting this error:

```
File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 679, in captureException
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 524, in capture
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 302, in build_msg
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 253, in get_handler
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 49, in __missing__
ImportError: No module named events
```
