### ISSUE TITLE
Problem with wsgi middleware when running under gunicorn with gaiohttp worker

### ISSUE THREAD

**Issue by urbaniak** [getsentry/raven-python#599]
Each request raises an error like this:

```
RuntimeError: Task got bad yield: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">...
```

It's caused by yield in the middleware:
```
    def __call__(self, environ, start_response):
        self.client.http_context(self.get_http_context(environ))

        try:
            iterable = self.application(environ, start_response)
        except Exception:
            self.handle_exception(environ)
            raise

        try:
            for event in iterable:
                yield event
```

**Comment by asvetlov** [comment]
What is your problem and how raven/sentry affects it?

**Comment by urbaniak** [comment]
Got a flask application running on gunicorn+gaiohttp worker, it's working well without Sentry middleware.

When enabling raven middleware the yield (https://github.com/getsentry/raven-python/blob/master/raven/middleware.py#L42) causes an error as in previous post:

```
Apr 19 07:48:50 hostname gunicorn[30853]: [2015-04-19 07:48:50 -0400] [30876] [ERROR] Error handling request
Apr 19 07:48:50 hostname gunicorn[30853]: Traceback (most recent call last):
Apr 19 07:48:50 hostname gunicorn[30853]: File "/home/app/.virtualenv/lib64/python3.4/site-packages/aiohttp/server.py", line 240, in start
Apr 19 07:48:50 hostname gunicorn[30853]: yield from handler
Apr 19 07:48:50 hostname gunicorn[30853]: File "/home/app/.virtualenv/lib64/python3.4/site-packages/aiohttp/wsgi.py", line 132, in handle_request
Apr 19 07:48:50 hostname gunicorn[30853]: riter = yield from riter
Apr 19 07:48:50 hostname gunicorn[30853]: File "/home/app/.virtualenv/lib64/python3.4/site-packages/raven/middleware.py", line 42, in __call__
Apr 19 07:48:50 hostname gunicorn[30853]: yield event
Apr 19 07:48:50 hostname gunicorn[30853]: RuntimeError: Task got bad yield: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n'
```

Tried to hack that, it started working when just returning the iterator from the Sentry middleware instead of looping over it and yielding.

Not sure it's a good solution.

**Comment by asvetlov** [comment]
Got it.
That's problem of gaiohttp gunicorn worker, not sentry.
Perhaps I should fix it though.

**Comment by xordoquy** [comment]
@asvetlov Should we close this issue then or is there some work to do on the raven's side ?

**Comment by asvetlov** [comment]
Yes, please close.

**Comment by xordoquy** [comment]
Thanks.
