### ISSUE TITLE
ImportError: No module named events

### ISSUE THREAD

**Issue by muthukumarclay** [getsentry/raven-python#616]
Getting the error

```
File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 679, in captureException
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 524, in capture
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 302, in build_msg
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 253, in get_handler
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 49, in __missing__
ImportError: No module named events
```

**Comment by xordoquy** [comment]
Which transport are you using ?

**Comment by muthukumarclay** [comment]
https

**Comment by javiromero** [comment]
Also seeing this error popup every few hours in the logs, I can't quite get how to reproduce it though. Here's the traceback:

```
2-45d7-9eb9-fbd44c41680a] INTERNAL ERROR: ImportError('No module named events',)
Traceback (most recent call last):
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/app/trace.py", line 125, in handle_failure
    einfo=einfo)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/contrib/celery/__init__.py", line 42, in process_failure_signal
    'kwargs': kwargs,
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/base.py", line 658, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 160, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/base.py", line 508, in capture
    **kwargs)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 107, in build_msg
    data = super(DjangoClient, self).build_msg(*args, **kwargs)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/base.py", line 286, in build_msg
    handler = self.get_handler(event_type)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/base.py", line 237, in get_handler
    return self.module_cache[name](self)
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/raven/base.py", line 49, in __missing__
    module, {}, {}, [class_name]), class_name)
ImportError: No module named events
```
Everything is up to date:
amqp==1.4.9
celery==3.1.19
kombu==3.0.33

There's a events module on the raven package and I can import it no problem from the python shell

```bash
$ ls
base.py   context.py   data        exceptions.py   __init__.py    middleware.pyc  scripts
base.pyc  context.pyc  events.py   exceptions.pyc  __init__.pyc   processors.py   transport
conf      contrib      events.pyc  handlers        middleware.py  processors.pyc  utils
```
```python
>>> from raven import events
>>> dir(events)
['BaseEvent', 'Exception', 'Message', 'Query', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'absolute_import', 'get_stack_info', 'iter_traceback_frames', 'logging', 'sys', 'to_unicode']
```
There's no other __raven__ packages installed. Please let me know how can I provide any more feedback.
This is related to #552

**Comment by dcramer** [comment]
Normally this would be a PATH issue, but we've also seen this with OOM. I think we can resolve some of it by guaranteeing raven imports all required submodules. That might not solve the issue of it trying to send an even when theres no memory to allocate, but it would at least ensure the error doesnt happen in an obscure way.

**Comment by Simanas** [comment]
Any updates on this one?

Getting this occasionally on our production servers. Is there any way I can prevent this?

```
ERROR 2016-08-24 02:50:19,889 models 28568 140125920855872 Unable to process log entry: No module named events
Traceback (most recent call last):
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 172, in sentry_exception_handler
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/base.py", line 655, in captureException
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 160, in capture
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/base.py", line 505, in capture
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 107, in build_msg
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/base.py", line 289, in build_msg
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/base.py", line 237, in get_handler
  File "/home/lifeguard/.virtualenvs/lifeguard2/local/lib/python2.7/site-packages/raven/base.py", line 49, in __missing__
ImportError: No module named events
```

**Comment by Simanas** [comment]
Up!

**Comment by dcramer** [comment]
I'm not entirely sure theres a way we can fix this. If you're getting OOM there's no guarantee we can report errors. My answer above still remains true. 

You can try doing "import raven.event" and see if that resolves it. If that at least ensures the error doesn't propagate up in this manerr we can change things to work that way.

**Comment by Simanas** [comment]
I am 100% sure it's not related to Out Of Memory scenario. We have resource monitoring in place. We are all good on memory at all times. 

I am also able to do "import raven.events" all the time. 

This error is very tough to reproduce as it starts happening only after about week of process operation. Once it's starts happening there is nothing unusual in terms of machine resources and it's happening in random way on exactly same requests at about 1/50 rate. 

Restarting uwsgi processes helps resolving it for next 7 days. So we ended up implementing cron job to do exactly that, but I find it as a duck tape fix instead of real one.

Just noticed that we were running 5.0.0 version, now updated to 5.27.1 I guess that might help...

**Comment by StephanErb** [comment]
FWIW, I have just seen something like this when a host was running out of file handles. @Simanas  maybe you have a similar problem?

**Comment by Simanas** [comment]
Good point! Worth checking. :) Will report later if this is the case.

**Comment by georgexsh** [comment]
@StephanErb same as you, this error disappeared after we fixed a fd leak bug.
