### ISSUE TITLE
UUID type serialisation error (py2.7)

### ISSUE THREAD

**Issue by jdu** [getsentry/raven-python#664]
Heya,

Having an issue running raven with a group of apps using psycopg2 and SQLAlchemy. I keep getting a flood of `<unknown>: None` messagtes in sentry, which are stemming from this log error I think:

```
2015-09-24 11:24:41+0000 [-] 'UUID' object has no attribute 'int'
2015-09-24 11:24:41+0000 [-] Traceback (most recent call last):
2015-09-24 11:24:41+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/raven/utils/serializer/manager.py", line 69, in transform
2015-09-24 11:24:41+0000 [-]     return serializer.serialize(value, **kwargs)
2015-09-24 11:24:41+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/raven/utils/serializer/base.py", line 83, in serialize
2015-09-24 11:24:41+0000 [-]     return repr(value)
2015-09-24 11:24:41+0000 [-]   File "/usr/lib/python2.7/uuid.py", line 192, in __repr__
2015-09-24 11:24:41+0000 [-]     return 'UUID(%r)' % str(self)
2015-09-24 11:24:41+0000 [-]   File "/usr/lib/python2.7/uuid.py", line 198, in __str__
2015-09-24 11:24:41+0000 [-]     hex = '%032x' % self.int
2015-09-24 11:24:41+0000 [-] AttributeError: 'UUID' object has no attribute 'int'
```

It looks like raven is trying to serialize a UUID object and failing on it, throwing the unknown error, which means I'm not seeing the original underlying error that's occurring. 

Is there way to extend the serializer to handle the UUID object type better on my end?

**Comment by dcramer** [comment]
What version of raven-python?

**Comment by jdu** [comment]
Sorry for the delayed response, i'm running `5.7.1`
