### ISSUE TITLE
Raven 5.9 logger handler not working in Django

### ISSUE THREAD

**Issue by tinycogio** [getsentry/raven-python#701]
Looks like there is an issue with Raven 5.9 / Django logger handler. During initializing Django (e.g. doing `django-admin.py`), it will error out complaining the the sentry handler does not have a 'handler' attribute.  Using Raven 5.8.1 works fine

This particular app is using Django 1.3 / Python 2.6, but not sure if that's really the issue. 

Django Logging setup
```python
        'sentry': {
            'level': 'ERROR',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        }
```

Stacktrace
```python
Traceback (most recent call last):
  File "<snip>/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "<snip>/lib/python2.6/site-packages/django/core/management/__init__.py", line 429, in execute_from_command_line
    utility.execute()
  File "<snip>/lib/python2.6/site-packages/django/core/management/__init__.py", line 368, in execute
    sys.stderr.write(self.main_help_text() + '\n')
  File "<snip>/lib/python2.6/site-packages/django/core/management/__init__.py", line 239, in main_help_text
    commands = get_commands().keys()
  File "<snip>/lib/python2.6/site-packages/django/core/management/__init__.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "<snip>/lib/python2.6/site-packages/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "<snip>/lib/python2.6/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "<snip>/lib/python2.6/site-packages/django/conf/__init__.py", line 139, in __init__
    logging_config_func(self.LOGGING)
  File "<snip>/lib/python2.6/site-packages/django/utils/dictconfig.py", line 553, in dictConfig
    dictConfigClass(config).configure()
  File "<snip>/lib/python2.6/site-packages/django/utils/dictconfig.py", line 352, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'sentry': Unable to configure handler 'sentry': 'module' object has no attribute 'handlers'
```

**Comment by vhermecz** [comment]
Might be an import loop, similarly to #508? Just a hunch.

**Comment by aaugustin** [comment]
I'm seeing a similar error with Raven 5.10. I'm not 100% sure it's the exact same issue, but it looks close enough to have a common root cause.

Here's the stack trace (with exception chaining, since this is on Python 3):

    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 382, in resolve
        found = getattr(found, frag)
    AttributeError: module 'raven.contrib.django.raven_compat' has no attribute 'handlers'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 558, in configure
        handler = self.configure_handler(handlers[name])
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 708, in configure_handler
        klass = self.resolve(cname)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 384, in resolve
        self.importer(used)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/raven/contrib/django/raven_compat/handlers.py", line 11, in <module>
        from raven.contrib.django.handlers import *  # NOQA
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/raven/contrib/django/handlers.py", line 11, in <module>
        from raven.contrib.django.models import client
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/raven/contrib/django/models.py", line 238, in <module>
        if ('raven.contrib.django' in settings.INSTALLED_APPS
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
        self._setup(name)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
        self._wrapped = Settings(settings_module)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 120, in __init__
        raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
    django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/myk/.virtualenvs/project_name/bin/django-admin", line 11, in <module>
        sys.exit(execute_from_command_line())
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
        utility.execute()
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/core/management/__init__.py", line 302, in execute
        settings.INSTALLED_APPS
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
        self._setup(name)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
        self._wrapped = Settings(settings_module)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/site-packages/django/conf/__init__.py", line 99, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/Users/myk/.virtualenvs/project_name/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/myk/Documents/project_name/settings/local.py", line 56, in <module>
        logging.config.dictConfig(LOGGING)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 795, in dictConfig
        dictConfigClass(config).configure()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 566, in configure
        '%r: %s' % (name, e))
    ValueError: Unable to configure handler 'sentry': The SECRET_KEY setting must not be empty.

**Comment by aaugustin** [comment]
Downgrading to Raven 5.7.2 — the version we were using previously — fixed the issue.

**Comment by aaugustin** [comment]
I bisected the regression to 02862d64c70e02f2d8f45aaeec0fa5e90e5f0144 (ping @dcramer).

That commit removes code that was clearly designed to delay the import `raven.contrib.django.models` in `raven.contrib.django.handlers` until it's actually needed. This is certainly the cause of this issue.

**Comment by dcramer** [comment]
Will revert that change -- I did basic tests and didn't catch this, sorry!

**Comment by dcramer** [comment]
Also my apologies for this slipping

**Comment by aaugustin** [comment]
Never mind, thanks for the quick fix!
