### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

### ISSUE THREAD

**Issue by jonasspott** [getsentry/raven-python#702]
I'm currently logging to both file and Sentry because a lot of 404 and exceptions is not logged in Sentry.
My log has a lot of these errors:

```
Traceback (most recent call last):
  File "/home/ubuntu/Env/Days/lib/python3.4/site-packages/raven/transport/threaded.py", line 173, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/ubuntu/Env/Days/lib/python3.4/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/ubuntu/Env/Days/lib/python3.4/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/home/ubuntu/Env/Days/lib/python3.4/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
```

My LOGGING in Django looks like this:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'root': {
        'level': 'WARNING',
        'handlers': ['file', 'sentry'],
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s '
                      '%(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'sentry': {
            'level': 'ERROR',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django/breeding.log'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['file', 'console'],
            'propagate': False,
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': ['file', 'console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['file', 'console'],
            'propagate': False,
        },
    },
}
```

_Running:_
Amazon EC2 Ubuntu 14.04
Django 1.9
Python 3.4.3 in environment (system runs Python 2.7 on 'python --version')
Raven 5.9.0

I have a self signed SSL Certificate with chmod 644.
I'm logged in as ubuntu user on EC2 - and system is running from ubuntu user.

On _runserver_ I'm getting a lot more things pushed to Sentry than running on uWSGI - any idea why that also? And what the error above is describing?

**Comment by mitsuhiko** [comment]
@jonasspott does the same thing happen with verify_ssl=0?

**Comment by jonasspott** [comment]
Yes, unfortunately.. I have tried this these settings:

RAVEN_CONFIG = {
    'dsn': 'https://xxx:xxx@app.getsentry.com/xxxxx?verify_ssl=0',
}

**Comment by mitsuhiko** [comment]
Are you using a proxy?

**Comment by jonasspott** [comment]
Nope - not as far as I know. I'm running on EC2 - on a standard setup. But if an EC2 Ireland instance is a proxy of something else I'm not proxying.

Could it be my self-signed SSL?

**Comment by mitsuhiko** [comment]
My guess is that this is an issue with SNI. I was hoping this would not trigger if verify-ssl is disabled but apparently not. Are you running a setup that requires SNI?

**Comment by mitsuhiko** [comment]
@jonasspott just to clarify: are you using a self hosted sentry behind a self signed cert or are you using app.getsentry.com?

**Comment by jonasspott** [comment]
Thank you for your time :)

1) I'm not 100% sure what SNI really is - but I havn't set up a specific SNI manually. Trying to give as much insight as possible. My current setup is Nginx, Django 1.9, EC2 instance
2) I'm using app.getsentry.com - not a hosted solution.

**Comment by mitsuhiko** [comment]
@jonasspott in that case the SSL certificate is entirely unrelated and so is the SNI information. I will investigate.

**Comment by knaperek** [comment]
I'm having the same issues also for a couple of months already, getting errors like this:

```python
Sentry responded with an error: <urlopen error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol> (url: https://sentry.io/api/<redacted>/store/)
Traceback (most recent call last):
  File "/var/www/myproject/env/lib/python2.7/site-packages/raven/transport/threaded.py", line 172, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/var/www/myproject/env/lib/python2.7/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/var/www/myproject/env/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/var/www/myproject/env/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol>

Request repr(): unavailable
```

**Comment by ashwoods** [comment]
@knaperek looks like an openssl issue. Mind opening another ticket as this one is quite old, and might be totally unrelated?
