### ISSUE TITLE
Django 1.9 exception if contrib apps are not loaded

### ISSUE THREAD

**Issue by kbrownlees** [getsentry/raven-python#705]
In Django 1.9 it became an error to import a model of an app before it is loaded (https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9):

>All models need to be defined inside an installed application or declare an explicit app_label. Furthermore, it isn’t possible to import them before their application is loaded. In particular, it isn’t possible to import models inside the root package of an application.

If you are running a lean django setup without users / content types the import of AbstractBaseUser / BaseUser triggers this condition and raven explodes.

````
Unable to process log entry: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. 
Traceback (most recent call last):
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 175, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/raven/base.py", line 698, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 142, in capture
    data.update(self.get_data_from_request(request))
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 56, in get_data_from_request
    from django.contrib.auth.models import AbstractBaseUser as BaseUser
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/home/kieran/.virtualenvs/grizzly-services/local/lib/python2.7/site-packages/django/db/models/base.py", line 103, in __new__
    "application was loaded. " % (module, name))
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. 
```

**Comment by dcramer** [comment]
Might make sense for us to remove any kind of actual association with ``django.contrib.auth`` and similar do feature testing on ``request.user`` to try and find attributes
