### ISSUE TITLE
Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1

### ISSUE THREAD

**Issue by croepha** [getsentry/raven-python#708]
python 3.5.1
raven 5.9.2

I am using self hosted Sentry.  Been using this configuration for a while, but recently upgraded a number of things in my docker image, but started getting some errors, tracked it to sentry, and I ran the Django admin command "raven test"

And this is what I get:
```
Client configuration:
  base_url       : http://sentry.service:9000
  project        : 1
  public_key     : <redacted>
  secret_key     : <redacted>

Sending a test message... Event ID was '910f2ce608344e96b05baf4e72e1d45c'
Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: http://sentry.service:9000/api/1/store/)
```
Then a few pages of JSON, then
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/raven/transport/threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python3.5/site-packages/raven/transport/requests.py", line 35, in send
    verify=self.verify_ssl, timeout=self.timeout)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 447, in prepare_body
    body = self._encode_params(data)
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 84, in _encode_params
    return to_native_string(data)
  File "/usr/local/lib/python3.5/site-packages/requests/utils.py", line 700, in to_native_string
    out = string.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
```
Then it looks like it repeats everything, but its escaped, like its running through repr():
```
b'Sentry responded with an error: \'ascii\' codec can\'t decode byte 0x9c in position 1: ordinal not in range(128) (url: http://sentry.service:9000/api/1/store/)\n{\'culprit\': \'__main__ in <module>\',\n \'event_id\': \'56f16b5caf124c0591bc8dd5c34c67ec\',\n \'extra\': {\'loadavg\': [0.91, 0.3, 0.18],\n           \'sys.argv\': ["\'/usr/local/bin/manage_streaming_engine\'",\n                        "\'raven\'",\n                        "\'test\'"],\n           \'user\': "\'root\'"},\n \'level\': 20,\n \'message\': \'This is a test message generated using ``raven test``\',\n \'modules\': {\'django\': \'1.9\',\n             \'django_s3_uploader\': \'0.1\',\n             \'python\': \'3.5.1\',\n             \'raven
...
```
This seems like it might be similar to this #653

I have a lot of custom stuff going on, so it might be be something on my end, I am still looking, but posting here incase you guys know what the issue is

**Comment by mitsuhiko** [comment]
Can you do me a favor and open this file: `/usr/local/lib/python3.5/site-packages/raven/transport/requests.py`

Then add this before line 34:

```python
print repr(data)
```

And attach the output (if it's save, otherwise you can mail it to me).

**Comment by croepha** [comment]
Should be sent now

**Comment by mitsuhiko** [comment]
Cheers. Looking through it.

**Comment by croepha** [comment]
I think this is a requests bug: https://github.com/kennethreitz/requests/issues/2938 https://github.com/kennethreitz/requests/issues/2933 https://github.com/kennethreitz/requests/issues/2930 Im confirming that

**Comment by mitsuhiko** [comment]
Yeah, code looks correct on our side i think. Was just seeing the same thing.

**Comment by mitsuhiko** [comment]
Going to close this. This is failing inside requests.

**Comment by croepha** [comment]
ok, Thanks for looking into this

**Comment by TheSavior** [comment]
We are getting this error still even with requests 2.10.0.
