### ISSUE TITLE
raven test - throws Client import error for 5.9.2 version

### ISSUE THREAD

**Issue by cypreess** [getsentry/raven-python#717]
For latest raven==5.9.2
```
$ raven test https://xx:xx@app.getsentry.com/xx
Traceback (most recent call last):
  File "/Users/cypreess/.virtualenvs/xx/bin/raven", line 7, in <module>
    from raven.scripts.runner import main
  File "/Users/cypreess/.virtualenvs/xx/lib/python3.5/site-packages/raven/scripts/runner.py", line 19, in <module>
    from raven import Client, get_version
ImportError: cannot import name 'Client'
```

Downgraded to 5.4.0 (minimal version required by raven-aiohttp) and test works

**Comment by dcramer** [comment]
I'm unable to reproduce this. It's likely somehow you have a corrupted package, and reinstalling it will resolve it.

**Comment by millerf** [comment]
+1 I have the same problem with python 2.7 and all raven-python version
