### ISSUE TITLE
Exception when formatting breadcrumbs

### ISSUE THREAD

**Issue by tinycogio** [getsentry/raven-python#766]
We're seeing an issue where the formatting is failing for the breadcrumbs. This ends up being a problem **as nothing will get sent to Sentry** so we didn't realize we were not getting errors any more until we noticed a slight increase in 5xx responses.

Can you catch exceptions while processing the breadcrumbs so we can at least see errors in Sentry without the breadcrumbs?

Using:
Python 2.7
Django 1.6.6
Raven ~~1.6.0~~ 5.16.0
Ubuntu 14.04

```
[2016-05-12 23:40:40,969] ERROR:sentry.errors.client error
 Unable to process log entry: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 175, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/base.py", line 762, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 271, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/base.py", line 591, in capture
    **kwargs)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 212, in build_msg
    data = super(DjangoClient, self).build_msg(*args, **kwargs)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/base.py", line 459, in build_msg
    crumbs = self.context.breadcrumbs.get_buffer()
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 42, in get_buffer
    processor(payload)
  File "/snip/CURRENT/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 72, in processor
    formatted_msg = msg % args
TypeError: not all arguments converted during string formatting
Unable to process log entry: not all arguments converted during string formatting```

**Comment by sempr** [comment]
I meet the same exception

**Comment by AndrewPashkin** [comment]
+1 

Here is my traceback:
```
Traceback (most recent call last):
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/handlers/logbook.py", line 49, in emit
    return self._emit(record)
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/handlers/logbook.py", line 100, in _emit
    **handler_kwargs
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/base.py", line 597, in capture
    **kwargs)
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/base.py", line 465, in build_msg
    crumbs = self.context.breadcrumbs.get_buffer()
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 42, in get_buffer
    processor(payload)
  File "/srv/rex/env/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 83, in processor
    formatted_msg = msg % args
TypeError: format requires a mapping
```

Versions:
Python 2.7.6
Raven 5.16.0

**Comment by mitsuhiko** [comment]
I'm wondering why the formatting errors come up. This should have failed with log reporting forever:

```
>>> import logging
>>> logging.basicConfig()
>>> logging.warning('%s', 'shit', 42)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file <stdin>, line 1
```

Unless this is a different case?

**Comment by AndrewPashkin** [comment]
@mitsuhiko, that was fast :+1:
