### ISSUE TITLE
Sentry Throws Exception Trying to log Exception

### ISSUE THREAD

**Issue by cancan101** [getsentry/raven-python#771]
```python-tb
Unable to process log entry: [u"'auth0|asdfgasdfg' value must be an integer."]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 175, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 766, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 249, in capture
    data.update(self.get_data_from_request(request))
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 164, in get_data_from_request
    user_info = self.get_user_info(user)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 146, in get_user_info
    'id': user.pk,
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 204, in inner
    self._setup()
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 351, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 960, in to_python
    params={'value': value},
ValidationError: [u"'auth0|asdfgasdfg' value must be an integer."]
```

**Comment by mitsuhiko** [comment]
Is your `request.user` broken? It would appear that this is actually an issue somewhere down your code and we fail to work with it. That said, we can probably handle that error nicer.

**Comment by cancan101** [comment]
yes, the user type _is_ misconfigured which is why the initial error is thrown. ideally the error would be logged so i can diagnose it (in this case I had to use the logs).
