### ISSUE TITLE
Unable to process log entry: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by oppianmatt** [getsentry/raven-python#791]
```

/usr/local/lib/python2.7/site-packages/raven/contrib/django/models.py:178

Message:
Unable to process log entry: 'NoneType' object has no attribute 'rfind'

exception:
Traceback (most recent call last):
,  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 175, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
,  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 768, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
,  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 268, in capture
    data.update(get_data_from_template(source, debug))
,  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/utils.py", line 56, in get_data_from_template
    'filename': os.path.basename(filename),
,  File "/usr/local/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
,AttributeError: 'NoneType' object has no attribute 'rfind'
```

raven==5.19.0

Don't know what log message is generating it to begin with since raven loses it.

**Comment by mitsuhiko** [comment]
Which version or Django are you using? Do you have some custom template loaders?

**Comment by oppianmatt** [comment]
Django==1.8.13

We have a custom template loader that if you're on the m. site it first checks for a m.html:

```
TEMPLATE_LOADERS = (
    'mobler.template.loaders.MobileLoader',
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)
```

But all it does is extends django.template.loaders.filesystem.Loader and tries to request:

```
template_name = template_name[:-5] + '.m.html'
```

**Comment by mitsuhiko** [comment]
My guess is that there is a template loader involved that does not set the debug info. Any chance you could share how the loader is implemented?

**Comment by oppianmatt** [comment]
```
class MobileLoader(django.template.loaders.filesystem.Loader):
    """
    This template loader replaces .html with .m.html and tries to load that
    """
    is_usable = True

    def load_template(self, template_name, template_dirs=None):
        request = get_current_request()
        if not request:
            return super(MobileLoader, self).load_template(template_name, template_dirs)
        if hasattr(request, 'is_mobile') and request.is_mobile and template_name.endswith('.html') and not template_name.endswith('.m.html'):
            template_name = template_name[:-5] + '.m.html'
        return super(MobileLoader, self).load_template(template_name, template_dirs)

```

get_current_request is using the thread local storage for storing a reference to the current request.

**Comment by mitsuhiko** [comment]
I have no idea how this works in Django but it would appear that there is no loadname for the template. I can work around this but this will just make it break in other ways. We're looking for a `template_debug` attribute on modern Django.

**Comment by mitsuhiko** [comment]
I pushed up a workaround for this, but this will just give you a broken filename now. Need to figure out what the core issue there is.

**Comment by mitsuhiko** [comment]
Aha. Apparently new Django only sets the debug info in debug now. Disappointing. Nothing we can do I think.

**Comment by oppianmatt** [comment]
note that the original error (the one sentry is trying to report) was in a normal template (not a m.html custom template loader), and was from going {{ item|first }} (with item set to None). 

Don't know what you mean about new django, but it was Django==1.8.13 so not the newest django.

**Comment by patroqueeet** [comment]
having the same error with a management command:

```
+ web/manage.py dbbackup --compress
Traceback (most recent call last):
  File "web/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 46, in new_execute
    'argv': sys.argv
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/raven/base.py", line 727, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 165, in capture
    data.update(get_data_from_template(source, debug))
  File "/opt/test.bob.kkd-partners.com/env/local/lib/python2.7/site-packages/raven/contrib/django/utils.py", line 56, in get_data_from_template
    'filename': os.path.basename(filename),
  File "/opt/test.bob.kkd-partners.com/env/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```
how to handle that?

**Comment by dcramer** [comment]
@patroqueeet im not really sure why the template would fail here, but its suggesting the template is returning a filename that isn't found. Are you using some kind of template loader that doesnt exist on disk, but might be returning a filepath? Ideally we'd handle this case and fail gracefully, which we're obviously not doing.

**Comment by patroqueeet** [comment]
hey, thanks for the fast answer. no templates involved at all. what we run is `dbbackup` from https://github.com/django-dbbackup/django-dbbackup and as I just learned is that it failed sending an email. 

that's all we do. the email thing will be fixed by us, but maybe the `fail gracefully` isn't too stable... but thats a wild guess...

**Comment by patroqueeet** [comment]
Just attempted to reproduce with raven 5.10.2 and also 6.0.0 and couldn't do so.  very strange. I'd say ignore this one pls until I can at least reproduce it...
