### ISSUE TITLE
tox errors out when running tests a second time

### ISSUE THREAD

**Issue by cjerdonek** [getsentry/raven-python#810]
After cloning this repo, I successfully ran `tox` in a fresh virtualenv after pip-installing tox. But whenever running tox a "second" time, I get the following error. It only works the second time when passing the `--recreate` flag. Here is what it looks like (for the `py35` environment):

    $ tox -e py35
    GLOB sdist-make: /.../raven-python/setup.py
    py35 inst-nodeps: /.../raven-python/.tox/dist/raven-5.23.0.zip
    ERROR: invocation failed (exit code 2), logfile: /.../raven-python/.tox/py35/log/py35-3.log
    ERROR: actionid: py35
    msg: installpkg
    cmdargs: [local('/.../raven-python/.tox/py35/bin/pip'), 'install', '-U', '--no-deps', '/.../raven-python/.tox/dist/raven-5.23.0.zip']
    env: <snip>

    Processing ./.tox/dist/raven-5.23.0.zip
    Building wheels for collected packages: raven
      Running setup.py bdist_wheel for raven: started
      Running setup.py bdist_wheel for raven: finished with status 'done'
      Stored in directory: /Users/chris_g4/Library/Caches/pip/wheels/fa/95/d1/6a3e34734b3d053c6ada3c966a79879c2949bd9a949b1fc25c
    Successfully built raven
    Installing collected packages: raven
      Found existing installation: raven 5.23.0
    Exception:
    Traceback (most recent call last):
      File "/.../raven-python/.tox/py35/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/.../raven-python/.tox/py35/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
        prefix=options.prefix_path,
      File "/.../raven-python/.tox/py35/lib/python3.5/site-packages/pip/req/req_set.py", line 736, in install
        requirement.uninstall(auto_confirm=True)
      File "/.../raven-python/.tox/py35/lib/python3.5/site-packages/pip/req/req_install.py", line 687, in uninstall
        '(at %s)' % (link_pointer, self.name, dist.location)
    AssertionError: Egg-link /.../raven-python does not match installed location of raven (at /.../raven-python/.tox/py35/lib/python3.5/site-packages)

    py35 installed: amqp==1.4.9,anyjson==0.3.3,beautifulsoup4==4.5.0,billiard==3.3.0.23,blinker==1.4,bottle==0.12.9,celery==3.1.23,click==6.6,Django==1.9.8,django-celery==3.1.17,exam==0.10.6,flake8==2.6.2,Flask==0.11.1,Flask-Login==0.3.2,itsdangerous==0.24,Jinja2==2.8,kombu==3.0.35,Logbook==1.0.0,MarkupSafe==0.23,mccabe==0.5.0,mock==2.0.0,nose==1.3.7,pbr==1.10.0,py==1.4.31,pycodestyle==2.0.0,pyflakes==1.2.3,pytest==2.9.2,pytest-django==2.9.1,pytest-timeout==0.4,pytz==2016.6.1,-e git+git@github.com:cjerdonek/raven-python.git@c3e170312df8d5efd64d33a55b7f66496117a86e#egg=raven,requests==2.10.0,six==1.10.0,tornado==4.4.1,waitress==0.9.0,WebOb==1.6.1,WebTest==2.0.23,Werkzeug==0.11.10
    __________________________________________________________________________________ summary __________________________________________________________________________________
    ERROR:   py35: InvocationError: /.../raven-python/.tox/py35/bin/pip install -U --no-deps /.../raven-python/.tox/dist/raven-5.23.0.zip (see /.../raven-python/.tox/py35/log/py35-3.log)
    
Some details:

    $ pip freeze
    pluggy==0.3.1
    py==1.4.31
    tox==2.3.1
    virtualenv==15.0.2
    $ python -V
    Python 3.5.1
    $ pip -V
    pip 8.1.2 from /.../.pyenv/versions/raven-python/lib/python3.5/site-packages (python 3.5)

**Comment by cjerdonek** [comment]
I posted PR #817 for this.

**Comment by ashwoods** [comment]
Tox ini has been rewritten with extras=test so I think this can be closed
