### ISSUE TITLE
raven 5.27.0 breaks Flask Application when a route does not exist

### ISSUE THREAD

**Issue by hitigon** [getsentry/raven-python#863]
tested raven 5.23, 5.24.1, 5.26.0 and 5.27.0 with OS X, Python 2.7.10, Flask 0.11.1

the latest release 5.27.0 breaks Flask App when hitting a non-existing route 

error log:

> 2016-09-17 17:14:51,067 [INFO] [werkzeug] 127.0.0.1 - - [17/Sep/2016 17:14:51] "GET /ccc HTTP/1.1" 500 -
Traceback (most recent call last):
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "<path>/lib/python2.7/site-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "<path>/lib/python2.7/site-packages/raven/contrib/flask.py", line 220, in before_request
    self.client.transaction.push(request.url_rule.rule)
AttributeError: 'NoneType' object has no attribute 'rule'

**Comment by kdeldycke** [comment]
Can confirm the issue.

**Comment by messense** [comment]
Seen the same issue.

**Comment by dcramer** [comment]
Actually that last commit isn't the entire fix.

**Comment by dcramer** [comment]
5.27.1 should resolve this
