### ISSUE TITLE
5.27.0 error on Django

### ISSUE THREAD

**Issue by magul** [getsentry/raven-python#864]
During using newest version I'm getting:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 131, in finish_response
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 36, in close
    SimpleHandler.close(self)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 259, in close
    self.result.close()
  File "/usr/local/lib/python2.7/dist-packages/django/http/response.py", line 309, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/middleware/__init__.py", line 108, in request_finished
    if self._txid:
AttributeError: 'SentryMiddleware' object has no attribute '_txid'
```
at every request.

Environment:
```
root@6f32543da243:/app# python --version
Python 2.7.9
root@6f32543da243:/app# pip freeze
alabaster==0.7.9
amqp==1.4.9
anyjson==0.3.3
apipkg==1.4
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
bcrypt==2.0.0
billiard==3.3.0.23
boto==2.38.0
celery==3.1.23
cffi==1.8.3
colorthief==0.2
contextlib2==0.5.4
coverage==4.2
decorator==4.0.10
Django==1.8
django-ajax-selects==1.3.6
django-appconf==1.0.2
django-celery==3.1.16
django-ckeditor==5.0.2
django-elasticache==0.0.3
django-filter==0.10.0
django-imagekit==3.2.6
django-merged-inlines==0.2
django-redis-cache==1.6.4
django-storages==1.1.8
django-suit==0.2.13
djangohmac==1.3.2
djangorestframework==3.2.4
djangorestframework-camel-case==0.2.0
docutils==0.12
drf-extensions==0.2.8
enum34==1.1.6
execnet==1.4.1
factory-boy==2.5.2
fancycompleter==0.5
gunicorn==19.3.0
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
Jinja2==2.8
kombu==3.0.35
Markdown==2.6.2
MarkupSafe==0.23
mock==1.0.1
ordereddict==1.1
pathlib2==2.1.0
pdbpp==0.8.3
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
pika==0.9.14
pilkit==1.1.13
Pillow==2.9.0
prompt-toolkit==1.0.7
psycopg2==2.6
ptyprocess==0.5.1
py==1.4.31
pycparser==2.14
pyflakes==1.3.0
Pygments==2.1.3
pylibmc==1.5.1
pyrepl==0.8.4
pytest==3.0.2
pytest-cache==1.0
pytest-cov==2.3.1
pytest-django==2.8.0
pytest-flakes==1.0.1
pytest-pep8==1.0.6
pytest-xdist==1.15.0
python-logstash==0.4.5
pytz==2015.4
raven==5.27.0
redis==2.10.3
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.3.1
sphinx-rtd-theme==0.1.9
statsd==3.2.1
traitlets==4.3.0
wcwidth==0.1.7
wmctrl==0.3
```

Installed applications looks like:
```
INSTALLED_APPS = (
    'raven.contrib.django.raven_compat',
    'suit',
    'ckeditor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django.contrib.sites',
    'djcelery',
    'storages',
    'merged_inlines',
    'rest_framework',
    'rest_framework.authtoken',
    'ajax_select',
)
```

**Comment by magul** [comment]
I've played around it for a few minutes and it occurs only for static assets. It ends up with 500 code (even if previously this assets ended up with 200, 304 or 404).

After that I also get:
```
Exception happened during processing of request from ('172.17.0.1', 54698)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 102, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 182, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

It occurs only when I'm trying to render meaningfull page. I was not able to see this problem requesting only static asset.

**Comment by dcramer** [comment]
521f272cd6ca4c6774e8c2265fb0f8a912612250 should fix this

**Comment by dcramer** [comment]
5.27.1 should resolve this
