### ISSUE TITLE
Get Top level Sentry exception using sentry logger

### ISSUE THREAD

**Issue by senseysensor** [getsentry/raven-python#873]
Hi, I get this exception with first seconds of app execution:

```python
Top level Sentry exception caught - failed creating log record
Notice, passed logger %s is not present in the logger manager
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/handlers/logging.py", line 66, in emit
    return self._emit(record)
  File "/usr/local/lib/python2.7/dist-packages/raven/handlers/logging.py", line 174, in _emit
    extra=extra, date=date, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 613, in capture
    self.send(**data)
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 706, in send
    message = self.encode(data)
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 748, in encode
    return zlib.compress(json.dumps(data).encode('utf8'))
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/json.py", line 51, in dumps
    return json.dumps(value, cls=BetterJSONEncoder, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 263, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/json.py", line 36, in default
    return super(BetterJSONEncoder, self).default(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
  File "/usr/lib/python2.7/threading.py", line 473, in __repr__
    assert self.__initialized, "Thread.__init__() was not called"
AssertionError: Thread.__init__() was not called```

Please help how should I fix that. I just've added 

```python
'sentry': {
            'level': 'WARN',
            'class': 'raven.handlers.logging.SentryHandler',
            'dsn': 'https://XXXXXX19c20607a4@sentry.io/10555',
        }````

to dictConfig handler section and added actually sentry logger.

**Comment by pebreo** [comment]
I have the same problem. Did you ever find the solution?
