### ISSUE TITLE
Sentry Flask Integration Not Working: Sentry.io responded with an error: http.client.BadStatusLine: <html>

### ISSUE THREAD

**Issue by ye** [getsentry/raven-python#907]
I've just upgraded our Flask (0.10.1) stack + raven-python (5.1.1) to the latest versions on pypi. Sentry stopped getting exceptions. I intentionally triggered a `TypeError` exception with `'%s %s' % 'foobar'` and was getting a `BadStatusLine` error. This is a hosted sentry setup. See below.

```bash
$ cat api/requirements.txt | grep lask
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.1
Flask==0.11.1
Flask-RESTful==0.3.5
Flask-Admin==1.4.2
Flask-Login==0.4.0

$ cat api/requirements.txt | grep raven
raven==5.32.0
```

Logs:
```
Sending message of length 5619 to https://sentry.io/api/37507
/store/
[2016-11-15 22:09:39,126] ERROR in app: Exception on /foo/bar [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/api/views/subscriptions.py", line 57, in get
    log.debug('Test Sentry Exception capture %s %s', 'should be triggered here')
  File "/usr/local/lib/python3.5/site-packages/structlog/stdlib.py", line 61, in debug
    return self._proxy_to_logger('debug', event, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/usr/local/lib/python3.5/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/usr/local/lib/python3.5/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/usr/local/lib/python3.5/site-packages/structlog/stdlib.py", line 275, in __call__
    event_dict['event'] = event_dict['event'] % args
TypeError: not enough arguments for format string


Sentry responded with an error: <html>
 (url: https://sentry.io/api/37507
/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python3.5/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python3.5/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.5/site-packages/raven/breadcrumbs.py", line 343, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/local/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.5/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <html>
```

I followed the setup detailed in [here](https://docs.sentry.io/clients/python/integrations/flask/). Do I miss something?

**Comment by mattrobenolt** [comment]
@mitsuhiko is there a bug here with something appending a newline after the project id in the URL? Or is that display just being wrapped?

**Comment by mattrobenolt** [comment]
@ye or is it possible that you have a newline at the end of your DSN?

**Comment by mitsuhiko** [comment]
That is very odd. Would it be possible to get the actual request that is being sent? Eg. Send it through a proxy that can record requests.

**Comment by mattrobenolt** [comment]
I'm guessing related to there being a newline character in the URL. Pretty confident that'd cause this error.

**Comment by mitsuhiko** [comment]
Is my guess but it looks like it urlencodes.

**Comment by ye** [comment]
Thanks guys to look into this. @mattrobenolt you are right on the money! Testing to remove the extra trailing newline to see if this works

**Comment by ye** [comment]
@mattrobenolt @mitsuhiko Yup, issue confirmed is due to human error 😂 . 

The back story was that I changed the DSN URL to be future proof (from getsentry.com to sentry.io) and inadvertently left a trailing `\n` in there (it's less apparent since we're using k8s secrets which b64encodes the content.) Removing that trailing newline character immediate solves the issue.

I am leaving this to you guys to decide whether a idiot proof sanitation like calling `.strip()` call is needed in init code or leave this as-is. To me this particular issue is resolved.

**Comment by ye** [comment]
Btw, when will `getsentry.com` domain get decommissioned? This [support page](https://sentry.io/organizations/maven/support/) still refer the support email to be support AT getsentry.com

**Comment by mattrobenolt** [comment]
Oh, it'll be a while before we can entirely remove it, and we don't have a formal schedule yet. It's not a super pressing concern yet, but I'll definitely update the email on that page. :)

**Comment by mitsuhiko** [comment]
Looks like this was a Python 3 specific issue? Not sure. In any case it behaved differently on 2.7.10 when I was testing it.

```
URLError: <urlopen error no host given>
```

Stripping automatically now.

**Comment by ye** [comment]
@mitsuhiko yes, we are on Python 3.5.2 and I think (but not sure) the reason you are getting a different error is due to the fact that Python 3.x has different built-in http client libs than Python 2.x?

**Comment by ye** [comment]
Matt and Armin, thanks again for the speedy response and fix!
