### ISSUE TITLE
Passing an exception class in ignore_exceptions causes raven error

### ISSUE THREAD

**Issue by mshang** [getsentry/raven-python#983]
Version: raven==6.0.0

According to the documentation for the `ignore_exceptions` client configuration option, I should be able to pass in either strings or exception classes. Passing in an exception class causes an error in raven. See code below.

`a.py`:
```
from raven import Client

client = Client('<omitted>',
    ignore_exceptions=[
        ZeroDivisionError,
    ],
)

try:
    1 / 0
except ZeroDivisionError:
    client.captureException()
```

```
(pyenv) Miless-MacBook:~ mshang$ python a.py
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 264, in handle_exception
    self.captureException(exc_info=exc_info, level='fatal')
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 799, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 615, in capture
    elif not self.should_capture(exc_info):
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 810, in should_capture
    elif any(exc_name.startswith(e[:-1]) for e in exclusions if e.endswith('*')):
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 810, in <genexpr>
    elif any(exc_name.startswith(e[:-1]) for e in exclusions if e.endswith('*')):
AttributeError: type object 'exceptions.ZeroDivisionError' has no attribute 'endswith'

Original exception was:
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    client.captureException()
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 799, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 615, in capture
    elif not self.should_capture(exc_info):
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 810, in should_capture
    elif any(exc_name.startswith(e[:-1]) for e in exclusions if e.endswith('*')):
  File "/Users/mshang/pyenv/lib/python2.7/site-packages/raven/base.py", line 810, in <genexpr>
    elif any(exc_name.startswith(e[:-1]) for e in exclusions if e.endswith('*')):
AttributeError: type object 'exceptions.ZeroDivisionError' has no attribute 'endswith'
```

**Comment by mshang** [comment]
Sorry, appears to be fixed in master.
